SET SEARCH_PATH TO armydb;
INSERT INTO "assign" (sold_id, type) VALUES ('19339', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('33998', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('49159', 'Major General');
INSERT INTO "assign" (sold_id, type) VALUES ('21474', 'Field Marshal');
INSERT INTO "assign" (sold_id, type) VALUES ('12498', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('14298', 'Lieutenant General');
INSERT INTO "assign" (sold_id, type) VALUES ('12398', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('13424', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('28613', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('13011', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('12300', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('14256', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('11088', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('13423', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('14345', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('21045', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('21040', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('22045', 'Major');
INSERT INTO "assign" (sold_id, type) VALUES ('13045', 'Havildar');
INSERT INTO "assign" (sold_id, type) VALUES ('29603', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('12245', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('10305', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('48563', 'Colonel');
INSERT INTO "assign" (sold_id, type) VALUES ('10923', 'Major General');
INSERT INTO "assign" (sold_id, type) VALUES ('12051', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('12105', 'Major');
INSERT INTO "assign" (sold_id, type) VALUES ('11145', 'Brigadier');
INSERT INTO "assign" (sold_id, type) VALUES ('12115', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('12045', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('10345', 'Lieutenant');
INSERT INTO "assign" (sold_id, type) VALUES ('10045', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('36099', 'Havildar');
INSERT INTO "assign" (sold_id, type) VALUES ('12345', 'Lieutenant');
INSERT INTO "assign" (sold_id, type) VALUES ('33728', 'Brigadier');
INSERT INTO "assign" (sold_id, type) VALUES ('23432', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('40386', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('31931', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('19338', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('33994', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('49158', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('22513', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('11053', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('27989', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('11046', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('13043', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('11238', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('11002', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('12402', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('13023', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('11045', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('14255', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('14245', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('22192', 'Soldier');
INSERT INTO "assign" (sold_id, type) VALUES ('12356', 'Captain');
INSERT INTO "assign" (sold_id, type) VALUES ('11305', 'Havildar');
INSERT INTO "assign" (sold_id, type) VALUES ('12005', 'Colonel');
INSERT INTO "assign" (sold_id, type) VALUES ('12498', 'Soldier');