SET SEARCH_PATH TO armydb;
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1053,'2000-01-1','Argentina','Bersa');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1054,'2001-02-2','Australia','Boeing Australia');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1055,'2005-03-3','Austria','Steyr Mannlicher');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1056,'2002-04-4','Azerbaijan','MDI Azerbaijan');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1057,'2003-05-5','Bangladesh','Defence Advancement Trading Company (DATCO)');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1058,'2001-06-6','Belgium','Fabrique Nationale de Herstal');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1059,'2002-07-7','Bosnia and Herzegovina','Pretis dd');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1060,'2006-08-8','Brazil','Avibras');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1061,'2005-09-9','Bulgaria','TEREM');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1062,'2001-10-10','India','Hindustan Aeronautics Limited');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1063,'2000-11-11','Argentina','Bersa');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1064,'2003-12-12','Australia','Boeing Australia');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1065,'2005-1-13','Austria','Steyr Mannlicher');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1066,'2002-2-14','Azerbaijan','MDI Azerbaijan');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1067,'2001-3-15','Bangladesh','Defence Advancement Trading Company (DATCO)');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1068,'2004-4-16','Belgium','Fabrique Nationale de Herstal');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1069,'2003-5-17','Bosnia and Herzegovina','Pretis dd');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1070,'2006-6-18','Brazil','Avibras');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1071,'2002-7-19','Bulgaria','TEREM');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1072,'2000-8-20','India','Hindustan Aeronautics Limited');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1073,'2001-9-21','Argentina','Bersa');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1074,'2005-10-22','Australia','Boeing Australia');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1075,'2004-11-23','Austria','Steyr Mannlicher');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1076,'2006-12-24','Azerbaijan','MDI Azerbaijan');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1077,'2003-1-25','Bangladesh','Defence Advancement Trading Company (DATCO)');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1078,'2004-2-26','Belgium','Fabrique Nationale de Herstal');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1079,'2001-3-27','Bosnia and Herzegovina','Pretis dd');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1080,'2003-4-28','Brazil','Avibras');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1081,'2002-5-1','Bulgaria','TEREM');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1082,'2001-6-2','India','Hindustan Aeronautics Limited');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1083,'2006-7-3','India','Hindustan Aeronautics Limited');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1084,'2003-8-4','India','Hindustan Aeronautics Limited');
INSERT INTO "manufacturing_details" (weapon_id, manufacturing_date, manufacting_location, company_name) VALUES (1085,'2004-9-5','India','Hindustan Aeronautics Limited');