SET SEARCH_PATH to armydb;
INSERT INTO medal VALUES('Ashok Chakra Award ');
INSERT INTO medal VALUES('Kirti Chakra ');
INSERT INTO medal VALUES('Shaurya Chakra ');
INSERT INTO medal VALUES('Sarvottam Yudh Seva Medal');
INSERT INTO medal VALUES('Yudh Seva Medal');
INSERT INTO medal VALUES('Ati Vishisht Seva Medal ');
INSERT INTO medal VALUES('Vishisht Seva Medal');
INSERT INTO medal VALUES('Bharat Award ');
INSERT INTO medal VALUES('Sarvottam Jeevan Raksha Padak'); INSERT INTO medal VALUES('Uttam Jeevan Raksha Padak'); 
INSERT INTO medal VALUES('Jeevan Raksha Padak');