SET SEARCH_PATH TO armydb;
INSERT INTO "weapons" (weapon_id,name) VALUES (1053, 'Glock-18');
INSERT INTO "weapons" (weapon_id,name) VALUES (1054, 'Dual Berettas');
INSERT INTO "weapons" (weapon_id,name) VALUES (1055, 'P250');
INSERT INTO "weapons" (weapon_id,name) VALUES (1056, 'Tec-9');
INSERT INTO "weapons" (weapon_id,name) VALUES (1057, 'CZ75-Auto');
INSERT INTO "weapons" (weapon_id,name) VALUES (1058, 'Desert Eagle');
INSERT INTO "weapons" (weapon_id,name) VALUES (1059, 'R8 Revolver');
INSERT INTO "weapons" (weapon_id,name) VALUES (1060, 'USP-S');
INSERT INTO "weapons" (weapon_id,name) VALUES (1061, 'P2000');
INSERT INTO "weapons" (weapon_id,name) VALUES (1062, 'Five-Seven');
INSERT INTO "weapons" (weapon_id,name) VALUES (1063, 'Nova');
INSERT INTO "weapons" (weapon_id,name) VALUES (1064, 'XM1014');
INSERT INTO "weapons" (weapon_id,name) VALUES (1065, 'Sawed-Off');
INSERT INTO "weapons" (weapon_id,name) VALUES (1066, 'M249');
INSERT INTO "weapons" (weapon_id,name) VALUES (1067, 'Negev');
INSERT INTO "weapons" (weapon_id,name) VALUES (1068, 'MAG-7');
INSERT INTO "weapons" (weapon_id,name) VALUES (1069, 'MAC-10');
INSERT INTO "weapons" (weapon_id,name) VALUES (1070, 'MP7');
INSERT INTO "weapons" (weapon_id,name) VALUES (1071, 'UMP-45');
INSERT INTO "weapons" (weapon_id,name) VALUES (1072, 'P90');
INSERT INTO "weapons" (weapon_id,name) VALUES (1073, 'PP-Bizon');
INSERT INTO "weapons" (weapon_id,name) VALUES (1074, 'MP9');
INSERT INTO "weapons" (weapon_id,name) VALUES (1075, 'Galil AR');
INSERT INTO "weapons" (weapon_id,name) VALUES (1076,'AK-47');
INSERT INTO "weapons" (weapon_id,name) VALUES (1077, 'SSG 08');
INSERT INTO "weapons" (weapon_id,name) VALUES (1078, 'SG 553');
INSERT INTO "weapons" (weapon_id,name) VALUES (1079, 'AWP');
INSERT INTO "weapons" (weapon_id,name) VALUES (1080, 'G3SG1');
INSERT INTO "weapons" (weapon_id,name) VALUES (1081, 'FAMAS');
INSERT INTO "weapons" (weapon_id,name) VALUES (1082, 'M4A4');
INSERT INTO "weapons" (weapon_id,name) VALUES (1083, 'M4A1-S');
INSERT INTO "weapons" (weapon_id,name) VALUES (1084, 'AUG');
INSERT INTO "weapons" (weapon_id,name) VALUES (1085, 'SCAR-20');